services:
  prometheus:
    user: ${PROMETHEUS_USER}
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - /home/ubuntu/dearbelly/deployment/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /home/ubuntu/prometheus/volume:/prometheus/data
    ports:
      - 9090:9090
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=15d'
    restart: always
    networks:
      - mynetwork

  grafana:
    user: ${GRAFANA_USER}
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - /home/ubuntu/grafana/volume:/var/lib/grafana
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge